// <auto-generated />

using System;
using HR_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace HR_Manager.Migrations
{
    [DbContext(typeof(HR_ManagerContext))]
    internal class HR_ManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HR_Manager.Models.Business", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("EmployeeId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("EmployeeId");

                b.ToTable("Business");
            });

            modelBuilder.Entity("HR_Manager.Models.Customer", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Address")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("EmployeeId")
                    .HasColumnType("int");

                b.Property<bool>("IsLargeCompany")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("EmployeeId");

                b.ToTable("Customer");
            });

            modelBuilder.Entity("HR_Manager.Models.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("Birthday")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FirstName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Employee");
            });

            modelBuilder.Entity("HR_Manager.Models.Business", b =>
            {
                b.HasOne("HR_Manager.Models.Employee", null)
                    .WithMany("Businesses")
                    .HasForeignKey("EmployeeId");
            });

            modelBuilder.Entity("HR_Manager.Models.Customer", b =>
            {
                b.HasOne("HR_Manager.Models.Employee", null)
                    .WithMany("Customers")
                    .HasForeignKey("EmployeeId");
            });
#pragma warning restore 612, 618
        }
    }
}